### ISSUE TITLE
Uncaught Error: Cannot set property length of [object Object] which has only a getter

### ISSUE THREAD

**Issue by smadapathi** [jurassix/joi-validation-strategy#6]
I am using joi-validation-strategy for react-validation-mixin but I am getting the error as
`Uncaught TypeError: Cannot set property length of [object Object] which has only a getter`.
Initially, I thought it could be because of older node and npm version but even after updating them I have the same issue. 
I am unable to run simple example of validation using this. If I remove joi, joi-validation-strategy, and when I use my own strategy, its working fine. Please let me know if I am missing something.

**Comment by jurassix** [comment]
@smadapathi can you provide your schema and maybe a simple example?

**Comment by smadapathi** [comment]
This is the example I am trying to use.
https://jurassix.gitbooks.io/docs-react-validation-mixin/content/examples/input.html

**Comment by smadapathi** [comment]
Apparently, this issue is not with joi-validation-strategy
https://github.com/feross/buffer/issues/79

@jurassix Thanks for your time.
